### PR TITLE
Bugfix: React List Key Issue

### LINKED ISSUE #319: Error in browser console: "console.js:288 Warning: Each child in a list should have a unique "key" prop."
**Describe the bug**

When a valid LinktaFlow object is returned from the LLM and rendered in the Flow component, the browser console displays the error "Warning: Each child in a list should have a unique 'key' prop."

This error is common in React applications when a list of JSX elements is created by calling Array.prototype.map() on a list of some kind and a unique 'key' prop is not provided. In this case, it appears the error may be caused by something internal to the ReactFlow or Dagre libraries.

**To Reproduce**
1. Sign in
2. Enter an input
3. Receive the response
4. Check the console

**Expected behavior**

No errors.

**Screenshots**

image

### PR DESCRIPTION
**Pull request by kinskiwu**
## Description
This PR fixes the console warning related to missing "key" prop in EdgeRenderer by ensuring all edges have unique keys, addressing the React Flow rendering issue.

- Removed unnecessary typing and ID mapping.
- Added `id` prop to the edge schema.

Fixes #319 

## Type of change

- [X]  🐛 Bug fix (non-breaking change which fixes an issue)

## How Can this be tested? Testing Plan to review this PR
- Spin up the app
- Create a new LinktaFlow
- Observe 
    - React Query:id in both nodes & edges
image
    - Console: no warning about unique key

## Checklist:

- [X] I have performed a self-review of my own code.
- [X] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [X] I have reviewed the [**Security Best Practices Document**](./docs/SECURITY_BEST_PRACTICES.md).
- [X] I have followed the [**Naming Conventions Guide**](./docs/NAMING_CONVENTIONS_GUIDE.md) for my changes.
- [X] I have ensured that my pull request title is descriptive.

## Additional Information:
- LinktaFLow validation for LLM response will be implemented in a separate PR

### CODE REVIEW

File: server/services/linktaFlowService.ts [hunk 1]
```diff
@@ -25,6 +26,16 @@ const createLinktaFlowService = () => {
...
   ): Promise<LinktaFlow> => {
+    const validateItem = (item: Node | Edge, type: 'node' | 'edge') => {
+      if (!item.id) {
+        logger.error(`${type} missing id`, {
+          item,
+          userInputId: userInputId.toString(),
+        });
+        throw new ValidationError(`${type} is missing required id`);
+      }
+    };
```
Comment (chriswillsflannery) [inline server/services/linktaFlowService.ts]: these nodes/edges are generated by the LLM right? what if it bombs out for some reason or generates ids with a wrong type? Should part of the validator function be to then add the [correct] id onto the item if it's incorrect or missing?

Comment (chriswillsflannery) [reply server/services/linktaFlowService.ts]: also, out of scope for this probably, but this is pretty much exactly what [zod](https://zod.dev/) is for

Comment (relandboyle) [reply server/services/linktaFlowService.ts]: > these nodes/edges are generated by the LLM right? what if it bombs out for some reason or generates ids with a wrong type? Should part of the validator function be to then add the [correct] id onto the item if it's incorrect or missing?

FWIW, the prompt includes a bit about using React Flow's Node and Edge types.

I think we don't have additional guards or validators because it just hasn't happened. Not saying it can't happen, but there are 500 of these objects in the dev database and I've never seen an error caused by the LLM response for any reason other than exceeding the token limit.

Comment (kinskiwu) [reply server/services/linktaFlowService.ts]: Thanks for the suggestion @chriswillsflannery. You're correct the nodes/edges including their ids are generated by the LLM. I did consider adding a fallback mechanism to generate missing ids (haven't thought about wrong types tho). However, the source and target in the edges must match the node ids they connect to which complicates the id generation logic. 

I think your idea about validating the linktaflow with zod is a good idea and we have an open ticket for that.

Comment (kinskiwu) [reply server/services/linktaFlowService.ts]: Thanks @relandboyle. I understand that the prompt includes React Flow's node and edge types, and it's great that we haven't encountered many issues so far.

That said, my opinion is that while we currently use the LLM to generate the React Flow object to simplify implementation, this approach introduces some challenges:
- Dependency on React Flow: If React Flow changes its structure in the future, we'll have to refactor the linktaFlow entity, increasing the maintenance burden.
- Violation of data modeling best practices: Ideally, our data model should remain independent of third-party libraries to ensure better flexibility and future-proofing.

I know we’ve agreed to revisit this post-MVP and this topic is def out of scope of this PR, but in the long term, we could consider creating a separate mechanism to convert the LLM response into a React Flow object (e.g., manually adding ids to nodes and edges). This would decouple React Flow from the data model and reduce the LLM overhead by simplifying the prompt to generate a simple tree instead of a React Flow object.

@chriswillsflannery Curious what's your opinion on this given your data modeling experience.

**Review by relandboyle — APPROVED** [review]

File: server/services/linktaFlowService.ts (hunk 1 above)
Comment (chriswillsflannery) [reply server/services/linktaFlowService.ts]: the structure returned from the LLM should be as library agnostic as possible

**Review by colinvandergraaf — APPROVED** [review]
