### PR TITLE
Login error resolution / simplification

### LINKED ISSUE #356: Warning: User Profile Not Found
**Describe the bug**
The nature of the error is a Mongo "duplicate key" error - occurs when there is an attempt to create a new User on the database with a duplicate value for a key that is part of a unique index.
This is likely related to failing to obtain the user's email from GitHub, so the email address is always null.
There may be two issues, or two circumstances where an email is null or an email is a duplicate
Image
The issue seems to be a result of user accounts getting out of sync in Firebase Auth vs. Mongo Atlas database.
Contributing factors:
- Firebase Auth setting: Link accounts by email vs. Create multiple accounts by identity provider
- Developers may delete accounts on either Firebase or Atlas without considering both

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by relandboyle**
This PR endeavors to resolve some nagging errors and broken functionality while removing, improving, or simplifying some parts of the application.

The main issues had to do with failed database queries which trigger alerts in the application, and the user's display name failing to populate on the database after signing up with email/password.

Previously, there were two static layout components; one for authenticated users which could render "private" views in the RouterOutlet, and one for unauthenticated users which would only render "public" views in the RouterOutlet. The display of one or the other of these layouts was conditionally based on the user authentication state. In addition, there was logic in the SignUp and SignIn views which would navigate to a private view ("/generate") upon successful authentication. 

The above became problematic because there is additional logic which should run after authentication (GET or POST to database, update Firebase auth token properties). Invoking navigate() immediately upon successful authentication would unmount the SignUp or SignIn component along with its queries and unexecuted logic. Orchestrating a conditional invocation of navigate() was insufficient because the change from one static layout to the other would also cause an unmount and re-render of the child component, i.e., the SignUp or SignIn view.

The solution may be to eliminate the dual static layouts, and use any available means to delay invocation of navigate() until after all other logic has completed. 

- Eliminate the "dual static layouts" concept to prevent problematic component re-renders
- Eliminate onAuthSuccess() method from SignInPage and SignUpPage
- Migrate StaticLayout (formerly _MainLayout_) and SideNav to CSS modules
- ~Implement "find one or create" logic for user profile queries on server~
- Generally rely on Firebase-provided UID to interact with users on the database, rather than Mongo ObjectId
- Correct property access on decoded Firebase auth token
- Remove references to email and remove DB index on email
- Add Skeleton for user name in SideNav UI
- Various updates to import statements, variable names, typos, small syntax errors, etc.
- Pass trace string to useFetchUserProfile() hook to track calls from various components
- Consistent implementation of timestamps across DB models
- Delete obsolete files: genAiController.ts, typeChecker.ts, UnauthorizedLayout.tsx, UnauthorizedLayout.module.css

Fixes #356 #236 #318 #384 

## Type of change

- [x]  🐛 Bug fix (non-breaking change which fixes an issue)

## How Can this be tested? Testing Plan to review this PR

What are the steps to test this change?

Generally interact with the app as a user. Delete your accounts on Firebase Auth and Mongo, create new accounts, submit queries, interact with Flows, etc. Use OAuth provider buttons as well as email/password sign-up and sign-in.

Expect reliable operation without errors.

## Checklist:

- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.

### CODE REVIEW

File: client/validators/validateUseremail.ts [hunk 1]
```diff
@@ -2,7 +2,7 @@ import { z } from 'zod';
 
 const disposableEmailDomains = [
   'mailinator.com',
-  'dispostable.com',
+  'dispostable.com', // is this a typo?
```
Comment (colinvandergraaf) [inline client/validators/validateUseremail.ts:5]: not a typo, but I think this service is deprecated. A quick search shows these are popular: 
https://maildrop.cc/  
https://maildrop.c 
https://incognitomail.co

File: server/controllers/userController.ts [hunk 2]
```diff
@@ -86,7 +118,7 @@ const createUserController = (
     }
   };
 
-  return { fetchUserProfile, createUserProfile };
+  return { fetchUserProfile: getUserByUid, createUserProfile };
 };
 
-export default createUserController;
+export default UserController;
```
Comment (colinvandergraaf) [inline server/controllers/userController.ts:114]: this is looking more intuitive now.

File: client/validators/validateUseremail.ts (hunk 1 above)
Comment (relandboyle) [reply client/validators/validateUseremail.ts:5]: https://www.npmjs.com/package/disposable-email-detector

**Review by colinvandergraaf — COMMENTED** [review]
I deleted accounts in firebase and mongoDB and created users with google, github and with password. I'm still getting the 'failed to fetch user profile' error with a 404 user not found on v1/users'  This also prevents me from creating any Linkta flows.  @kinskiwu are you able to create flows on this branch?

File: client/features/auth-pages/SignInPage.tsx [hunk 3]
```diff
@@ -1,17 +1,17 @@
...
+import { useGoogleAuthMutation } from '@hooks/useSignInWithGoogle';
 import { useGithubAuthMutation } from '@hooks/useSignInWithGitHub';
 import { useSignInWithEmailAndPasswordMutation } from '@/hooks/useSignInWithEmailAndPassword';
 import { useForm, type SubmitHandler } from 'react-hook-form';
-import { z } from 'zod';
-import { zodResolver } from '@hookform/resolvers/zod';
 import useFetchUserProfile from '@/hooks/useFetchUserProfile';
-import useCreateUserProfileMutation from '@/hooks/useCreateUserProfileMutation';
-import { useQueryClient } from '@tanstack/react-query';
+// import SnackBarNotification from '@components/common/SnackBarNotification';
```
Comment (colinvandergraaf) [inline client/features/auth-pages/SignInPage.tsx]: If we're using useNotification in lieu of these maybe these should be deleted?

File: client/hooks/useSignInWithGoogle.ts [hunk 4]
```diff
@@ -17,9 +18,11 @@ export const useGoogleAuthMutation = (): UseMutationResult<
   return useMutation<GoogleAuthResult, Error, void>({
     mutationFn: async () => {
       const provider = new GoogleAuthProvider();
+      provider.addScope('email');
```
Comment (colinvandergraaf) [inline client/hooks/useSignInWithGoogle.ts:20]: Didn't know  the `useScope()` method existed. Nice!

File: server/controllers/genAiController.ts
Comment (colinvandergraaf) [inline server/controllers/genAiController.ts:1]: 🔥

**Review by colinvandergraaf — APPROVED** [review]
As you mentioned earlier, I did notice the name issue when logging in with username and password, but otherwise great job on this!

File: client/features/auth-pages/SignInPage.tsx (hunk 3 above)
Comment (relandboyle) [reply client/features/auth-pages/SignInPage.tsx]: @colinvandergraaf Yes. There is a bit of commented code throughout this branch which I will delete.

**Comment by relandboyle** [comment]
> I deleted accounts in firebase and mongoDB and created users with google, github and with password. I'm still getting the 'failed to fetch user profile' error with a 404 user not found on v1/users' This also prevents me from creating any Linkta flows. @kinskiwu are you able to create flows on this branch?

@colinvandergraaf Can I mark this one resolved?

File: client/hooks/useSignInWithGitHub.ts
Comment (kinskiwu) [inline client/hooks/useSignInWithGitHub.ts:1]: The firebase auth token is retrieved in the Axios config in `config/axios.ts` so we are not using the token returned from this hook. Probably better to remove the related code.

File: client/hooks/useSignInWithGoogle.ts
Comment (kinskiwu) [inline client/hooks/useSignInWithGoogle.ts:1]: Same comment about removing token related code as in `useSignInWithGitHub.ts`.

File: client/features/auth-pages/SignInPage.tsx [hunk 5]
```diff
@@ -69,10 +63,16 @@ const SignInPage = () => {
 
   const handleGithubAuthClick = async () => {
     try {
-      await githubAuthMutation.mutateAsync();
-      await handleAuthSuccess('');
+      const githubAuthResult = githubAuthMutation.mutateAsync();
```
Comment (kinskiwu) [inline client/features/auth-pages/SignInPage.tsx]: MutateAsync returns a Promise so we should await it right?

File: client/features/auth-pages/SignUpPage.tsx [hunk 6]
```diff
@@ -81,10 +63,16 @@ const SignUpPage = () => {
 
   const handleGithubAuthClick = async () => {
     try {
-      await githubAuthMutation.mutateAsync();
-      await handleAuthSuccess('');
+      const githubAuthResult = githubAuthMutation.mutateAsync();
```
Comment (kinskiwu) [inline client/features/auth-pages/SignUpPage.tsx]: Same comment about awaiting this async func as in `SignInPage`.

File: server/controllers/userController.ts [hunk 7]
```diff
@@ -9,33 +9,34 @@ const logger = log4js.getLogger('[User Controller]');
  * Creates user controller with the provided services.
  * @returns {object} User controller.
  */
-const createUserController = (
-  userService: ReturnType<typeof createUserService>,
-) => {
+const UserController = (userService: ReturnType<typeof createUserService>) => {
```
Comment (kinskiwu) [inline server/controllers/userController.ts:12]: Since this is a factory function and there are many more of them in our API, probably better to adhere to the naming convention starting with a verb like the one we had before.

File: server/controllers/userController.ts [hunk 8]
```diff
@@ -9,33 +9,34 @@ const logger = log4js.getLogger('[User Controller]');
...
-      if (user) {
+      if (linktaUser) {
         res.locals.userProfile = {
-          email: user.email,
-          name: user.name,
-          profilePicture: user.profilePicture,
-          settings: user.settings,
+          name: linktaUser.name,
+          profilePicture: linktaUser.profilePicture,
+          authProvider: linktaUser.authProvider,
```
Comment (kinskiwu) [inline server/controllers/userController.ts]: The client doesn't need the authProvider so maybe leave it out?

File: server/controllers/userController.ts [hunk 9]
```diff
@@ -46,33 +47,65 @@ const createUserController = (
...
+  //     logger.error('Error fetching user profile for userId', error);
+
+  //     next(new InternalServerError('Failed to fetch user profile'));
+  //   }
+  // };
+
   /**
    * Creates a user profile.
    */
   const createUserProfile = async (
```
Comment (kinskiwu) [inline server/controllers/userController.ts:44]: We probably want to keep the code related to `name` so that when a user signs up by email and password our API can store the provided name.

File: server/controllers/userController.ts [hunk 10]
```diff
@@ -86,7 +119,7 @@ const createUserController = (
     }
   };
 
-  return { fetchUserProfile, createUserProfile };
+  return { fetchUserProfile: getUserByUid, createUserProfile };
```
Comment (kinskiwu) [inline server/controllers/userController.ts]: Instead of using a variable here probably better to use the new method name `getUserByUid`.

File: server/routes/userRouter.ts [hunk 11]
```diff
@@ -1,19 +1,35 @@
 import { Router } from 'express';
 import type { Request, Response } from 'express';
-import createUserController from '@/controllers/userController';
+import UserController from '@/controllers/userController';
```
Comment (kinskiwu) [inline server/routes/userRouter.ts:3]: Same comment about keeping the factory name as it was to keep it consistent across the backend.

File: client/features/auth-pages/SignUpPage.tsx [hunk 12]
```diff
@@ -94,16 +82,15 @@ const SignUpPage = () => {
   };
 
   const onSubmit: SubmitHandler<FormData> = async (data) => {
-    const { email, password, name } = data;
```
Comment (kinskiwu) [inline client/features/auth-pages/SignUpPage.tsx:97]: Consider using the useCreateUserProfileMutation func here to create a new userProfile for when a user signs up by email and password. Currently, no username is displayed when we sign up by email and password. Keep in mind a userProfile should only be created after a user has been successfully authenticated via firebase.

**Review by kinskiwu — COMMENTED** [review]
Thanks for the good work @relandboyle! Just a few small changes. Let me know when you're done and I will review the changes and approve the PR.

**Comment by kinskiwu** [comment]
> > I deleted accounts in firebase and mongoDB and created users with google, github and with password. I'm still getting the 'failed to fetch user profile' error with a 404 user not found on v1/users' This also prevents me from creating any Linkta flows. @kinskiwu are you able to create flows on this branch?
> 
> @colinvandergraaf Can I mark this one resolved?

@relandboyle I think we can mark it as resolved since we discussed it at standup yesterday and clarified that it was an issue with the .env file on Colin's local machine. I didn't get this error following the same steps.

File: server/controllers/userController.ts (hunk 7 above)
Comment (kinskiwu) [reply server/controllers/userController.ts:12]: It is better to revert back to `createUserController` to remain consistent with the naming convention of our factory function pattern and the rest of the backend.

File: server/routes/linktaFlowRouter.ts [hunk 13]
```diff
@@ -3,19 +3,19 @@ import type { Request, Response } from 'express';
 import createLinktaFlowController from '@/controllers/linktaFlowController';
 import createLinktaFlowService from '@/services/linktaFlowService';
 import isAuthorized from '@middleware/firebaseAuthMiddleware';
-import createUserService from '@/services/userService';
+// import createUserService from '@/services/userService';
```
Comment (kinskiwu) [inline server/routes/linktaFlowRouter.ts:6]: Remember to remove the commented-out code from this file

File: server/routes/userRouter.ts [hunk 14]
```diff
@@ -1,19 +1,35 @@
...
 
 const userRouter = Router();
 
-// Instantiate the services
+// Instantiate the service
 const userService = createUserService();
 
 // Instantiate the controller with the services
-const userController = createUserController(userService);
+const userController = UserController(userService);
```
Comment (kinskiwu) [inline server/routes/userRouter.ts:16]: Recommend reverting back to `createUserController`.

File: client/features/auth-pages/SignInPage.tsx [hunk 15]
```diff
@@ -25,84 +22,71 @@ type FormData = z.infer<typeof userSignInSchema>;
...
-        console.error('Failed to create user profile:', error);
-      }
-    }
-  };
-
   const handleGoogleAuthClick = async () => {
     try {
-      await googleAuthMutation.mutateAsync();
-      await handleAuthSuccess('');
+      await googleAuthMutation.mutateAsync().then(() => {
```
Comment (kinskiwu) [inline client/features/auth-pages/SignInPage.tsx:41]: Just leaving a comment here to remind you to create a new ticket to address the issue with Google and Github Oauth users currently being able to log in to the app without a userProfile.

File: client/features/auth-pages/SignInPage.tsx [hunk 16]
```diff
@@ -25,84 +22,71 @@ type FormData = z.infer<typeof userSignInSchema>;
...
       );
+      navigate('/home-page');
     }
   };
 
   const handleGithubAuthClick = async () => {
     try {
-      await githubAuthMutation.mutateAsync();
-      await handleAuthSuccess('');
+      await githubAuthMutation.mutateAsync().then(() => {
```
Comment (kinskiwu) [inline client/features/auth-pages/SignInPage.tsx:58]: Same comment as in `handleGoogleAuthClick`

**Review by kinskiwu — APPROVED** [review]

**Review by chrisr0892 — APPROVED** [review]
